// Traditional turtle board. 144 tiles.
export const TURTLE = {
  name: "Turtle",
  code: "MJS01f8nmP8DHDKDNNNP85KDMMMNP86NMQWPWPWPWCMNNC4CYFNNNMQWC2CgTPVPWCMNNNC4CYZ4CYPYDNNMQWPVPVPWCMNNNP84NMQWPWPWPWCMNNP86KDMMMNP85HDKDNNN",
};

// Custom board resembling a cat's head. 112 tiles.
export const CAT = {
  name: "Cat",
  code: "MJS01b9cyMMPz7MMNMPz5NMMNZGD2XQ2XQ2XQ2XCNNMPzDPz2MMPz2PzDHDMPz2MZK22XQ2XCNZ2XDZKD2XQHD2XCNZH22XDNZ2XDNPz2Z2X2NZ2XFZGD2XQ2XQ2XCN",
};

// Custom board resembling a dog. 182 tiles.
export const DOG = {
  name: "Dog",
  code: "MJS01xbDdQWDQWCMMMMMQWPWPW4QWCKDMMMMQWPWPWFQWCMPzDMMPzDQWPWPWFQWCKDMMMMQWPWPW4MMZcVQcVCMMMQWCNNPz4MPzFMNNNNC4CYPXFZ4WQ4WCMMNNNNZ4W6Z4WCMNNNNNP86JDNP8DNP86NP8DNZKDDYQDY6ZDYPY2N",
};

// Smaller version of the turtle board. 62 tiles.
export const TINYTURTLE = {
  name: "Tiny Turtle",
  code: "MJS0185BCNNNMMMNNPz2QWPWPWCMPzFQWPWPWCMNPz2QWPWPWCMP8DNNMMMNN",
};
